learning_log/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),

    # my_blog url
    re_path(r'', include(('learning_logs.urls', 'learning_logs'),
        namespace='learning_logs')),

    # users url
    re_path(r'^users/', include(('users.urls', 'users'), namespace=None))
]

learning_logs/urls.py
"""learning_logs의 URL 패턴을 정의한다."""

from django.urls import re_path

from . import views

urlpatterns = [
    #홈페이지
    re_path(r'^$', views.index, name='index'),

    # 주제를 모두 표시한다.
    re_path(r'^topics/$', views.topics, name='topics'),
    # 주제 하나에 대한 세부사항 페이지
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # 새 주제를 추가하는 페이지
    re_path(r'^new_topic/$', views.new_topic, name = 'new_topic'),

    # 새 항목을 추가하는 페이지
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry,
     name = 'new_entry'),

     # 항목을 편집하는 페이지
     re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
     name = 'edit_entry'),

     # 항목의 자세한 페이지
     re_path(r'^read_entry/(?P<entry_id>\d+)/$', views.read_entry,
     name = 'read_entry'),

     # 주제를 삭제 하는 페이지
     re_path(r'^topics/(?P<topic_id>\d+)/remove/$', views.topics_remove,
     name='topics_remove'),

     # 내용을 삭제하는 페이지
     re_path(r'topics/(?P<entry_id>\d+)/entry_remove/$', views.entries_remove,
     name='entries_remove'),

     #댓글을 추가하는 페이지
     re_path(r'^read_entry/(?P<entry_id>\d+)/comment/$',
      views.add_comment_to_entry, name= 'add_comment_to_entry'),

     #댓글을 삭제하기
     re_path(r'^entry/(?P<comment_id>\d+)/comment/$',
     views.comment_delete, name ='comment_delete'),
]

users/urls.py
"""users 앱의 URL 패턴을 정의하는 파일"""

from django.urls import re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    # 로그인 페이지
    re_path(r'^login/$',
     auth_views.LoginView.as_view(template_name='users/login.html'),
      name = 'login'),
    re_path(r'^register/$', views.register, name='register'),

    # 로그아웃 페이지
    re_path(r'^logout/$', views.logout_view, name ='logout'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Topic(models.Model):
    """topic은 사용자가 공부하고 있는 주제이다."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """모델에 관한 정보를 문자열 형태로 변환한다."""
        return self.text

class Entry(models.Model):
    """주제에 관해 공부한 내용"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """모델에 관한 정보를 문자열 형태로 반환한다."""
        if self.text[:] > self.text[:50]:
            return self.text[:50] + "..."
        else:
            return self.text[:]

class Comment(models.Model):
    entry = models.ForeignKey(Entry, related_name='comments',
     on_delete = models.CASCADE)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry, Comment


class TopicForm(forms. ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'public']
        lavels = {'text' : '', 'public':'public'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text',]
        labels = {'text' : ''}
        widgets = {'text' : forms.Textarea(attrs={'cols':80})}
        labels = {'text':'',}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text',]
        lavels = {'text':'',}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse


from .models import Topic, Entry, Comment
from .forms import TopicForm, EntryForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """학습 로그 홈페이지"""
    return render(request, 'learning_logs/index.html')

# this should really be a method on a custom ModelManager
def _get_topics_for_user(user):
    " returns a queryset of topics the user can access "
    q = Q(public=True)
    # if django < 1.10 you want "user.is_authenticated()" (with parens)
    if user.is_authenticated:
       # adds user's own private topics to the query
       q = q | Q(public=False, owner=user)

    return Topic.objects.filter(q)

def topics(request):
    """주제를 표현한다"""
    topics = _get_topics_for_user(request.user).order_by('date_added')
    form = TopicForm()
    context = {'topics': topics, 'form': form}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    topics = _get_topics_for_user(request.user)
    topic = get_object_or_404(topics, id=topic_id)
    form = TopicForm()
    # here we're passing the filtered queryset, so
    # if the topic "topic_id" is private and the user is either
    # anonymous or not the topic owner, it will raise a 404
    if topic.owner == request.user:
            entries = topic.entry_set.order_by('-date_added')
            context = {'topic': topic, 'entries': entries, 'form': form}
            return render(request, 'learning_logs/topic.html', context)
    else:
        entries = topic.entry_set.order_by('-date_added')
        context = {'topic': topic, 'entries': entries, 'form': form}
    return render(request, 'learning_logs/public_topic.html', context)

def read_entry(request, entry_id):
    "내용을 자세히 보여준는 페이지를 반환한다."
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    context = {'entry': entry, 'topic':topic}
    return render(request, 'learning_logs/read_entry.html', context)

@login_required
def new_topic(request):
    """새 주제 추가"""
    if request.method != 'POST':
        # 들어온 데이터가 없을 때는 새 폼을 만든다.
        form = TopicForm()
    else:
        # POST 데이터를 받아서 처리한다.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """특정 주제에 관한 새 항목을 추가"""
    topic = get_object_or_404(Topic, id=topic_id)
    check_user = check_topic_owner(request, topic)

    if request.method != 'POST':
        # 전송된 데이터가 없으므로 빈 폼을 만든다.
        form = EntryForm()
    else:
        # 받은 POST 데이터를 처리한다.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic_id]))

    context = {'topic':topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """기존 항목을 편집한다."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    check_user = check_topic_owner(request, topic)

    if request.method != 'POST':
        # 첫 요청이므로 폼을 현재 텍스트로 채운다.
        form = EntryForm(instance=entry)
    else:
        # POST 데이터를 받았으므로 받은 데이터를 처리한다.
        form = EntryForm(data=request.POST)
        return HttpResponseRedirect(reverse('learning_logs:topic',
                                    args=[topic.id]))

    context = {'entry': entry, 'topic':topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def add_comment_to_entry(request, entry_id):
    "댓글을 달수있게한다."
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic

    if request.method != "POST":
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.entry = entry
            new_comment.author = request.user
            new_comment.save()
            return HttpResponseRedirect(reverse('learning_logs:read_entry',
                                        args=[entry_id]))

    context = {'entry':entry, 'topic':topic, 'form':form, }
    return render(request, 'learning_logs/add_comment_to_entry.html',
            context)

@login_required
def topics_remove(request, topic_id):
    """주제를 삭제한다."""
    topic = get_object_or_404(Topic, id=topic_id)
    check_user = check_topic_owner(request, topic)

    topic.delete()
    return HttpResponseRedirect(reverse('learning_logs:topics'))

@login_required
def entries_remove(request, entry_id):
    """내용을 삭제한다."""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    topic_id = entry.topic.id
    check_user = check_topic_owner(request, topic)

    entry.delete()
    return HttpResponseRedirect(reverse('learning_logs:topic',
                                args=[topic_id]))

@login_required
def comment_delete(request, comment_id):
    """댓글을 삭제한다."""
    comment = Comment.objects.get(id=comment_id)
    entry = comment.entry
    # 댓글의 유저를 확인한다.
    if comment.author != request.user:
        raise Http404

    comment.delete()
    return HttpResponseRedirect(reverse('learning_logs:read_entry',
                                args=[entry.id]))


def check_topic_owner(request, topic):
    """현재 유저가 올바른 유저인지 체크한다"""
    if topic.owner != request.user:
        raise Http404

learning_logs/templates/learning_logs/add_comment_to_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:read_entry' entry.id %}">
    <strong>{{ topic }}</strong></h2></a>
{% endblock %}

{% block content %}
    <h1>New comment</h1>
    <form action="{% url 'learning_logs:add_comment_to_entry' entry.id %}"
     method="post" class="post-form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-success">Send</button>
        {% endbuttons %}
    </form>
{% endblock %}

learning_logs/templates/learning_logs/add_comment_to_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:read_entry' entry.id %}">
    <strong>{{ topic }}</strong></h2></a>
{% endblock %}

{% block content %}
    <h1>New comment</h1>
    <form action="{% url 'learning_logs:add_comment_to_topic' entry.id %}"
     method="post" class="post-form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-success">Send</button>
        {% endbuttons %}
    </form>
{% endblock %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
              Learning Log</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit entry:</h2>
{% endblock %}

{% block content %}

  <form action="{% url 'learning_logs:edit_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  </form>

{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Track your learning.</h1>
  </div>
{% endblock %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a>
    to make your own Learning Log, and list the topics you're learning about.
  </h2>
  <h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
  </h2>
{% endblock %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock %}
{% block content %}

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name='submit' class="btn btn-primary">add entry</button>
    {% endbuttons %}
</form>

{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='post'
     class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
  </form>

{% endblock %}

learning_logs/templates/learning_logs/public_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>{{ topic }}</h1>
  <h3>author - {{ topic.owner }}</h3>
{% endblock %}

{% block content %}

{% for entry in entries %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small>
          <form action="{% url 'learning_logs:read_entry' entry.id %}"
          method='post' class="form">
                {% csrf_token %}

                {% buttons %}
                  <button name="submit"
                  class="btn btn-success">Read More</button>
                {% endbuttons %}
            </form>
      </small>
    </h3>
  </div>
  <div class="panel-body">
    {{ entry.text|truncatechars:150|linebreaks }}
  </div>
</div><!-- panel -->
{% empty %}
  There is nothing
{% endfor %}

{% endblock %}

learning_logs/templates/learning_logs/read_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">
  {{ topic }}</a></h2>
{% endblock %}

{% block content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      {{ entry.date_added|date:'M d, Y H:i' }}
    </div>
    <div class="panel-body">
      {{ entry.text|linebreaks }}
    </div>
  </div>
  <form action="{% url 'learning_logs:add_comment_to_entry' entry.id %}"
    class="form-inline">
    <button class="btn btn-success">
      Add Comment
    </button>
  </form>
  <div class="detailBox">
    <div class="titleBox">
      <label>Comment Box</label>
        <button type="button" class="close" aria-hidden="true">&times;</button>
    </div>

    <div class="commentBox">
      <p>What is your comment?</p>
    </div>
    <div class="actionBox">
      <ul class="commentList">
        <li>
          {% for comment in entry.comments.all %}
          <form action="{% url 'learning_logs:comment_delete' comment.id %}"
          method='post' class="form">
                {% csrf_token %}
                <div class="text-right">
                  {% buttons %}
                    <button name="submit"
                    class="btn btn-danger">Delete Comment</button>
                  {% endbuttons %}
                </div>
            </form>
              <div class="commentText">
                <p class="">{{ comment.text|linebreaks }}</p>
                  <span class="date sub-text">{{ comment.created_date }}</span>
                  <storng>{{ comment.author }}</storng>
                </div>
              {% empty %}
                <p>No comments here yet :(</p>
        </li>
      </ul>
    </div>
  </div>
    </div>
  {% endfor %}
{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h1>{{ topic }}
      <small>
        <form action="{% url 'learning_logs:topics_remove' topic.id %}"
        method='post' class="form">
              {% csrf_token %}
              <div class="text-right">
                {% buttons %}
                  <button name="submit"
                  class="btn btn-danger">Delete topic</button>
                {% endbuttons %}
              </div>
          </form>
      </small>
  </h1>
  <h3>author:{{ topic.owner }}</h3>
{% endblock %}

{% block content %}

      <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              edit entry</a>
              <form action="{% url 'learning_logs:read_entry' entry.id %}"
              method='post' class="form">
                    {% csrf_token %}

                    {% buttons %}
                      <button name="submit"
                      class="btn btn-success">Read More</button>
                    {% endbuttons %}
                </form>
              <form action="{% url 'learning_logs:entries_remove' entry.id %}"
              method='post' class="form">
                    {% csrf_token %}

                    {% buttons %}
                      <button name="submit"
                      class="btn btn-danger">Delete Entry</button>
                    {% endbuttons %}
                </form>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|truncatechars:150|linebreaks }}
      </div>
    </div><!-- panel -->
    {% empty %}
      There is nothing
    {% endfor %}

{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>Topics</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
        <small>author: {{ topic.owner }}</small>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
  <h3>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
  </h3>

{% endblock %}